// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'data': string;
  'down': string;
  'hmm': string;
  'tooltip': string;
  'up': string;
}
export const cssExports: CssExports;
export default cssExports;
